/**
 * InspectIA — léxico de iconos.
 *
 * **Generado desde icons.json. No editar a mano:** editar el JSON y correr `npm run icons`.
 *
 * ICON mapea CONCEPTO DE NEGOCIO → glifo. Es la capa que hay que usar: si mañana un
 * concepto cambia de glifo, cambia acá y en ningún otro lado.
 */
import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Antenna,
  Aperture,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUpFromLine,
  BadgeCheck,
  Ban,
  Banknote,
  Barcode,
  Bell,
  BellRing,
  Binary,
  BookOpen,
  Bot,
  Boxes,
  BrainCog,
  Briefcase,
  Building2,
  Cable,
  Calculator,
  CalendarClock,
  CalendarDays,
  Camera,
  Cctv,
  ChartColumn,
  ChartLine,
  ChartPie,
  Check,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleHelp,
  CirclePause,
  CirclePlay,
  CircleSlash,
  CircleUser,
  CircleX,
  CircuitBoard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  ClockArrowUp,
  Cloud,
  Cog,
  Columns3,
  Construction,
  Contact,
  Container,
  Copy,
  Cpu,
  Database,
  Download,
  Drone,
  Droplet,
  EllipsisVertical,
  ExternalLink,
  Eye,
  Factory,
  FileSpreadsheet,
  FileText,
  Filter,
  Flame,
  Focus,
  Folder,
  Forklift,
  Gauge,
  GitCommitHorizontal,
  Grid2x2,
  Handshake,
  HardDrive,
  HardHat,
  Headset,
  History,
  Hourglass,
  House,
  Info,
  Key,
  Languages,
  Laptop,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LifeBuoy,
  Link,
  Linkedin,
  List,
  ListChecks,
  Loader,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Minus,
  Monitor,
  Moon,
  Network,
  Package,
  PackageCheck,
  PackageOpen,
  PackageSearch,
  PackageX,
  PanelLeft,
  Pencil,
  Percent,
  Phone,
  Plane,
  PlugZap,
  Plus,
  Power,
  Presentation,
  Printer,
  QrCode,
  Radar,
  RadioTower,
  Receipt,
  Recycle,
  RefreshCw,
  RotateCcw,
  Route,
  Ruler,
  SatelliteDish,
  Save,
  Scale,
  ScanBarcode,
  ScanEye,
  ScanLine,
  Search,
  Server,
  Settings,
  Settings2,
  Share2,
  ShieldAlert,
  ShieldCheck,
  Ship,
  Sigma,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Sun,
  Table,
  Tablet,
  Target,
  Thermometer,
  Timer,
  TrainFront,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Truck,
  Upload,
  Usb,
  User,
  UserCheck,
  UserCog,
  UserPlus,
  Users,
  Video,
  Warehouse,
  Waypoints,
  Webhook,
  Wifi,
  WifiOff,
  Workflow,
  Wrench,
  X,
  Zap,
} from "lucide-react";

export const ICON = {
  oee: Gauge, // OEE
  realtime: Activity, // Tiempo real
  running: CirclePlay, // En producción
  stopped: CirclePause, // Detenido
  stopUnplanned: TriangleAlert, // Parada no planificada
  stopPlanned: CalendarClock, // Parada programada
  noData: CircleSlash, // Sin datos
  defect: CircleX, // Defecto / scrap
  company: Building2, // Empresa
  plant: Factory, // Planta
  line: GitCommitHorizontal, // Línea de producción
  machine: Cog, // Máquina
  sku: Boxes, // SKU
  warehouse: Warehouse, // Depósito
  shift: Clock, // Turno
  workOrder: ClipboardList, // Orden de producción
  operator: HardHat, // Operario
  terminal: Monitor, // Terminal de planta
  noPermission: Lock, // Sin permisos
  modules: LayoutGrid, // Módulos
  visionInspection: ScanEye, // Inspección por visión
  inbound: Truck, // Recepción de mercadería
  mobileCount: Smartphone, // Conteo desde el celular
  drone: Drone, // Dron
  camera: Cctv, // Cámara de seguridad
  outbound: PackageCheck, // Control de pedidos
  agent: Bot, // Agente de IA
  phone: Phone, // Teléfono
  email: Mail, // Correo
  linkedin: Linkedin, // LinkedIn
  whatsapp: MessageCircle, // WhatsApp
  included: Check, // Incluido en el plan
  notIncluded: Minus, // No incluido en el plan
} satisfies Record<string, LucideIcon>;

export type IconConcept = keyof typeof ICON;

/** Subconjunto aprobado de Lucide. Cualquier glifo fuera de esta lista se rechaza en review. */
export const ALLOWED_ICONS = [
  "activity",
  "antenna",
  "aperture",
  "arrow-down-to-line",
  "arrow-left",
  "arrow-right",
  "arrow-up-from-line",
  "badge-check",
  "ban",
  "banknote",
  "barcode",
  "bell",
  "bell-ring",
  "binary",
  "book-open",
  "bot",
  "boxes",
  "brain-cog",
  "briefcase",
  "building-2",
  "cable",
  "calculator",
  "calendar-clock",
  "calendar-days",
  "camera",
  "cctv",
  "chart-column",
  "chart-line",
  "chart-pie",
  "check",
  "chevron-down",
  "chevron-right",
  "circle-alert",
  "circle-check",
  "circle-dot",
  "circle-help",
  "circle-pause",
  "circle-play",
  "circle-slash",
  "circle-user",
  "circle-x",
  "circuit-board",
  "clipboard-check",
  "clipboard-list",
  "clock",
  "clock-arrow-up",
  "cloud",
  "cog",
  "columns-3",
  "construction",
  "contact",
  "container",
  "copy",
  "cpu",
  "database",
  "download",
  "drone",
  "droplet",
  "ellipsis-vertical",
  "external-link",
  "eye",
  "factory",
  "file-spreadsheet",
  "file-text",
  "filter",
  "flame",
  "focus",
  "folder",
  "forklift",
  "gauge",
  "git-commit-horizontal",
  "grid-2x2",
  "handshake",
  "hard-drive",
  "hard-hat",
  "headset",
  "history",
  "hourglass",
  "house",
  "info",
  "key",
  "languages",
  "laptop",
  "layers",
  "layout-dashboard",
  "layout-grid",
  "life-buoy",
  "link",
  "linkedin",
  "list",
  "list-checks",
  "loader",
  "lock",
  "log-in",
  "log-out",
  "mail",
  "map-pin",
  "menu",
  "message-circle",
  "minus",
  "monitor",
  "moon",
  "network",
  "package",
  "package-check",
  "package-open",
  "package-search",
  "package-x",
  "panel-left",
  "pencil",
  "percent",
  "phone",
  "plane",
  "plug-zap",
  "plus",
  "power",
  "presentation",
  "printer",
  "qr-code",
  "radar",
  "radio-tower",
  "receipt",
  "recycle",
  "refresh-cw",
  "rotate-ccw",
  "route",
  "ruler",
  "satellite-dish",
  "save",
  "scale",
  "scan-barcode",
  "scan-eye",
  "scan-line",
  "search",
  "server",
  "settings",
  "settings-2",
  "share-2",
  "shield-alert",
  "shield-check",
  "ship",
  "sigma",
  "sliders-horizontal",
  "smartphone",
  "sparkles",
  "sun",
  "table",
  "tablet",
  "target",
  "thermometer",
  "timer",
  "train-front",
  "trash-2",
  "trending-down",
  "trending-up",
  "triangle-alert",
  "trophy",
  "truck",
  "upload",
  "usb",
  "user",
  "user-check",
  "user-cog",
  "user-plus",
  "users",
  "video",
  "warehouse",
  "waypoints",
  "webhook",
  "wifi",
  "wifi-off",
  "workflow",
  "wrench",
  "x",
  "zap",
] as const;

export type AllowedIcon = (typeof ALLOWED_ICONS)[number];

/**
 * Nombre aprobado de Lucide → componente, resuelto en tiempo de compilación.
 *
 * Existe para que `Icon` no importe el mapa `icons` de lucide-react, que es la librería
 * entera. Generado: no se edita a mano.
 */
export const GLYPH = {
  activity: Activity,
  antenna: Antenna,
  aperture: Aperture,
  "arrow-down-to-line": ArrowDownToLine,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-from-line": ArrowUpFromLine,
  "badge-check": BadgeCheck,
  ban: Ban,
  banknote: Banknote,
  barcode: Barcode,
  bell: Bell,
  "bell-ring": BellRing,
  binary: Binary,
  "book-open": BookOpen,
  bot: Bot,
  boxes: Boxes,
  "brain-cog": BrainCog,
  briefcase: Briefcase,
  "building-2": Building2,
  cable: Cable,
  calculator: Calculator,
  "calendar-clock": CalendarClock,
  "calendar-days": CalendarDays,
  camera: Camera,
  cctv: Cctv,
  "chart-column": ChartColumn,
  "chart-line": ChartLine,
  "chart-pie": ChartPie,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "circle-dot": CircleDot,
  "circle-help": CircleHelp,
  "circle-pause": CirclePause,
  "circle-play": CirclePlay,
  "circle-slash": CircleSlash,
  "circle-user": CircleUser,
  "circle-x": CircleX,
  "circuit-board": CircuitBoard,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  clock: Clock,
  "clock-arrow-up": ClockArrowUp,
  cloud: Cloud,
  cog: Cog,
  "columns-3": Columns3,
  construction: Construction,
  contact: Contact,
  container: Container,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  download: Download,
  drone: Drone,
  droplet: Droplet,
  "ellipsis-vertical": EllipsisVertical,
  "external-link": ExternalLink,
  eye: Eye,
  factory: Factory,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  filter: Filter,
  flame: Flame,
  focus: Focus,
  folder: Folder,
  forklift: Forklift,
  gauge: Gauge,
  "git-commit-horizontal": GitCommitHorizontal,
  "grid-2x2": Grid2x2,
  handshake: Handshake,
  "hard-drive": HardDrive,
  "hard-hat": HardHat,
  headset: Headset,
  history: History,
  hourglass: Hourglass,
  house: House,
  info: Info,
  key: Key,
  languages: Languages,
  laptop: Laptop,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  "life-buoy": LifeBuoy,
  link: Link,
  linkedin: Linkedin,
  list: List,
  "list-checks": ListChecks,
  loader: Loader,
  lock: Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  mail: Mail,
  "map-pin": MapPin,
  menu: Menu,
  "message-circle": MessageCircle,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  network: Network,
  package: Package,
  "package-check": PackageCheck,
  "package-open": PackageOpen,
  "package-search": PackageSearch,
  "package-x": PackageX,
  "panel-left": PanelLeft,
  pencil: Pencil,
  percent: Percent,
  phone: Phone,
  plane: Plane,
  "plug-zap": PlugZap,
  plus: Plus,
  power: Power,
  presentation: Presentation,
  printer: Printer,
  "qr-code": QrCode,
  radar: Radar,
  "radio-tower": RadioTower,
  receipt: Receipt,
  recycle: Recycle,
  "refresh-cw": RefreshCw,
  "rotate-ccw": RotateCcw,
  route: Route,
  ruler: Ruler,
  "satellite-dish": SatelliteDish,
  save: Save,
  scale: Scale,
  "scan-barcode": ScanBarcode,
  "scan-eye": ScanEye,
  "scan-line": ScanLine,
  search: Search,
  server: Server,
  settings: Settings,
  "settings-2": Settings2,
  "share-2": Share2,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  ship: Ship,
  sigma: Sigma,
  "sliders-horizontal": SlidersHorizontal,
  smartphone: Smartphone,
  sparkles: Sparkles,
  sun: Sun,
  table: Table,
  tablet: Tablet,
  target: Target,
  thermometer: Thermometer,
  timer: Timer,
  "train-front": TrainFront,
  "trash-2": Trash2,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  "triangle-alert": TriangleAlert,
  trophy: Trophy,
  truck: Truck,
  upload: Upload,
  usb: Usb,
  user: User,
  "user-check": UserCheck,
  "user-cog": UserCog,
  "user-plus": UserPlus,
  users: Users,
  video: Video,
  warehouse: Warehouse,
  waypoints: Waypoints,
  webhook: Webhook,
  wifi: Wifi,
  "wifi-off": WifiOff,
  workflow: Workflow,
  wrench: Wrench,
  x: X,
  zap: Zap,
} satisfies Record<AllowedIcon, LucideIcon>;

/** Cuatro tamaños y ninguno más. No se acepta un número arbitrario, a propósito. */
export const ICON_SIZE = {
  meta: 14,
  ui: 16,
  empty: 20,
  brand: 24,
} as const;

export const ICON_STROKE = 1.5;
