/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TymeoRouteImport } from './routes/tymeo'
import { Route as RoiRouteImport } from './routes/roi'
import { Route as RecepcionRouteImport } from './routes/recepcion'
import { Route as IndexRouteImport } from './routes/index'

const TymeoRoute = TymeoRouteImport.update({
  id: '/tymeo',
  path: '/tymeo',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiRoute = RoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const RecepcionRoute = RecepcionRouteImport.update({
  id: '/recepcion',
  path: '/recepcion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recepcion': typeof RecepcionRoute
  '/roi': typeof RoiRoute
  '/tymeo': typeof TymeoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recepcion': typeof RecepcionRoute
  '/roi': typeof RoiRoute
  '/tymeo': typeof TymeoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recepcion': typeof RecepcionRoute
  '/roi': typeof RoiRoute
  '/tymeo': typeof TymeoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recepcion' | '/roi' | '/tymeo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recepcion' | '/roi' | '/tymeo'
  id: '__root__' | '/' | '/recepcion' | '/roi' | '/tymeo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecepcionRoute: typeof RecepcionRoute
  RoiRoute: typeof RoiRoute
  TymeoRoute: typeof TymeoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tymeo': {
      id: '/tymeo'
      path: '/tymeo'
      fullPath: '/tymeo'
      preLoaderRoute: typeof TymeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi': {
      id: '/roi'
      path: '/roi'
      fullPath: '/roi'
      preLoaderRoute: typeof RoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recepcion': {
      id: '/recepcion'
      path: '/recepcion'
      fullPath: '/recepcion'
      preLoaderRoute: typeof RecepcionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecepcionRoute: RecepcionRoute,
  RoiRoute: RoiRoute,
  TymeoRoute: TymeoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
